Document: kwick-sdig
Title: Debian kwick-sdig Manual
Author: <insert document author here>
Abstract: This manual describes what kwick-sdig is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kwick-sdig/kwick-sdig.sgml.gz

Format: postscript
Files: /usr/share/doc/kwick-sdig/kwick-sdig.ps.gz

Format: text
Files: /usr/share/doc/kwick-sdig/kwick-sdig.text.gz

Format: HTML
Index: /usr/share/doc/kwick-sdig/html/index.html
Files: /usr/share/doc/kwick-sdig/html/*.html


